### ISSUE TITLE
/regenerate command conflicts

### ISSUE THREAD

**Issue by KhaozFrost** [Polymeta/WonderTrade#1]
This... might not be the best command to use for the plugin as worldgeneration type plugins and/or protection plugins tend to use this same mapping.

**Comment by Polymeta** [comment]
Hi there! this sounds indeed unfortunate. I will probably end up giving it an alias or something like that to workaround the issue. In the meantime, can you not just tab through and select which regenerate command you want to use or do they all look the same? Not sure if my 1.12 knowledge is kind of messing with me here.

**Comment by Polymeta** [comment]
This has been addressed with the 1.1 release now, let me know if you have any more issues!
