### ISSUE TITLE
Pool blacklist 

### ISSUE THREAD

**Issue by ojcastillo29** [Polymeta/WonderTrade#4]
At this time, the only blacklist is for the pokemon players are adding to the pool/wt. The ability to not allow specified species to the generated pool would allow us to keep custom pokemon and/or legends from the pool and obtained in a different way.

**Comment by Polymeta** [comment]
Hey there, you are correct that there was a bug that on pool generation the blacklist got ignored. 

That however got fixed in v1.2, so now the blacklist applies to both, players adding Pokémon or the pool being (re)generated. 

Hope this helps!
