### ISSUE TITLE
Enhancement/Request - Potential UI to display the pokemon within the pool

### ISSUE THREAD

**Issue by ojcastillo29** [Polymeta/WonderTrade#5]
A potential command to allow permissible players to view what pokemon are within the current wt pool  via UI would be great. 

Allows the ability to see what is potentially obtainable and/or see if any pokemon that are not expected to be in the pool, due to forgetting to add to blacklist and what not, for possible removal.

**Comment by Polymeta** [comment]
This is going to become part of the next release for cobblemon 1.6, will keep this open to try it, but will close it on release
