### ISSUE TITLE
Cooldown not working

### ISSUE THREAD

**Issue by Senpaizzy** [Polymeta/WonderTrade#6]
Hi, my server seems to be having an issue where our wondertrade cooldown isn't working. people are able to instantly use it again.

```
  "poolSize": 20,
  "cooldownEnabled": true,
  "cooldown": 120,
  "blacklist": [],
  "poolMinLevel": 1,
  "poolMaxLevel": 100,
```

Nothing else has been edited, so I'm unsure where to problem lies.

**Comment by Polymeta** [comment]
Most likely to do with permissions, did you assign the `wondertrade.command.trade.bypass` permission by accident?

**Comment by Senpaizzy** [comment]
nvm figured it out, was an error on permissions side.

**Comment by Senpaizzy** [comment]
> Most likely to do with permissions, did you assign the `wondertrade.command.trade.bypass` permission by accident?

it looks like it, thank you
