### ISSUE TITLE
regenerate pool command

### ISSUE THREAD

**Issue by BrainDifff** [Polymeta/WonderTrade#7]
no opped players can use /regeneratepool and even when I remove the permission in luckperms they can still use it

**Comment by BrainDifff** [comment]
and crashes the server if they put a really high number in

**Comment by ModifiedMC** [comment]
Also having this issue, just trying to generate a pool of 500.. it works fine with 100 so its not a matter of the triple digits being the issue but definitely the cause of these crashes.
[crash-2023-11-04_22.36.51-server.txt](https://github.com/Polymeta/WonderTrade/files/13257983/crash-2023-11-04_22.36.51-server.txt)
[crash-2023-11-05_00.03.46-server.txt](https://github.com/Polymeta/WonderTrade/files/13257984/crash-2023-11-05_00.03.46-server.txt)

**Comment by ModifiedMC** [comment]
Im not having the issue of not being able to run the command, but the /regeneratepool command has crashed my server twice now

**Comment by Polymeta** [comment]
Ah never forgot to reply to this, but essentially generating the pool is a blocking operation. I have not gotten around to looking into that, so for the time being, the best workaround is what you already have observed and ensure the pool number is not too high while I take time to look into this.

**Comment by Scizith** [comment]
my server crashes regardless of the size i try to regenerate. have tried /regenerate as well as /regeneratepool. also cant get non ops to be able to use the wondertrade command, regardless of permissions set.

**Comment by Polymeta** [comment]
I've made some changes to the way the pool is regenerated to ensure that high numbers don't just stall/crash the server. 

I was able to do 30000 in my test server without issue now. 

This fix is due to come out when cobblemon 1.6 releases
